"""Audit log constants - event categories and event types."""


class AuditEventCategory:
    AUTH = "AUTH"
    VIDEO = "VIDEO"
    PATIENT = "PATIENT"
    PROVIDER = "PROVIDER"
    SYSTEM = "SYSTEM"
    ADMIN = "ADMIN"
    USER = "USER"


class AuditEventType:
    # AUTH
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    LOGOUT = "LOGOUT"
    REGISTER = "REGISTER"
    PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST"
    PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS"
    EMAIL_VERIFIED = "EMAIL_VERIFIED"
    TOKEN_REFRESHED = "TOKEN_REFRESHED"
    # PATIENT
    PATIENT_UPDATED = "PATIENT_UPDATED"
    PATIENT_DEACTIVATED = "PATIENT_DEACTIVATED"
    # PROVIDER
    PROVIDER_UPDATED = "PROVIDER_UPDATED"
    PROVIDER_DEACTIVATED = "PROVIDER_DEACTIVATED"
    REGISTER_FAILURE = "REGISTER_FAILURE"
    TOKEN_REUSE_DETECTED = "TOKEN_REUSE_DETECTED"
    EMAIL_VERIFICATION_FAILED = "EMAIL_VERIFICATION_FAILED"
    PASSWORD_RESET_FAILURE = "PASSWORD_RESET_FAILURE"
    # VIDEO
    VIDEO_SESSION_STARTED = "VIDEO_SESSION_STARTED"
    VIDEO_SESSION_ENDED = "VIDEO_SESSION_ENDED"
    VIDEO_SESSION_JOINED = "VIDEO_SESSION_JOINED"
    # ADMIN
    ADMIN_ACTION = "ADMIN_ACTION"
