"""Audit log failure reason constants — used in write_audit_log(failure_reason=...)."""


class FailureReason:
    # Register
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"

    # Login
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    ACCOUNT_NOT_ACTIVE = "ACCOUNT_NOT_ACTIVE"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    PHONE_NOT_VERIFIED = "PHONE_NOT_VERIFIED"

    # Refresh token
    REFRESH_TOKEN_REUSE_DETECTED = "REFRESH_TOKEN_REUSE_DETECTED"

    # Email verification
    EMAIL_VERIFICATION_TOKEN_INVALIDATED = "EMAIL_VERIFICATION_TOKEN_INVALIDATED"
    EMAIL_VERIFICATION_TOKEN_ALREADY_USED = "EMAIL_VERIFICATION_TOKEN_ALREADY_USED"
    EMAIL_VERIFICATION_TOKEN_EXPIRED = "EMAIL_VERIFICATION_TOKEN_EXPIRED"

    # OTP - Email verification
    OTP_INVALID = "OTP_INVALID"
    OTP_EXPIRED = "OTP_EXPIRED"
    OTP_ALREADY_USED = "OTP_ALREADY_USED"
    OTP_INVALIDATED = "OTP_INVALIDATED"
    OTP_CODE_MISMATCH = "OTP_CODE_MISMATCH"

    # Password reset
    RESET_TOKEN_ALREADY_USED = "RESET_TOKEN_ALREADY_USED"
    RESET_TOKEN_INVALIDATED = "RESET_TOKEN_INVALIDATED"
    RESET_TOKEN_EXPIRED = "RESET_TOKEN_EXPIRED"
