name: Docker Build

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  docker-build:
    name: Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Git SHA
        id: vars
        run: echo "sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: ./services/video-conference
          tags: qarevo-api:${{ steps.vars.outputs.sha }}
          load: true

      - name: Build Web image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/web
          tags: qarevo-web:${{ steps.vars.outputs.sha }}
          load: true

      - name: Run Trivy vulnerability scanner on API image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: qarevo-api:${{ steps.vars.outputs.sha }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: false

      - name: Run Trivy vulnerability scanner on Web image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: qarevo-web:${{ steps.vars.outputs.sha }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: false