from pydantic import BaseModel, Field, field_validator
from typing import Optional, Dict, Any
from uuid import UUID, uuid4

class AIRequestContext(BaseModel):
    """Correlation and audit tracking parameters across microservices."""
    correlation_id: UUID = Field(default_factory=uuid4, description="Tracks request life cycle")
    operator_id: str = Field(..., description="The ID of the clinician initiating the draft")
    patient_id: str = Field(..., description="Target patient ID for safety policy checking")

class AIPolicyGate(BaseModel):
    """Compliance guardrails checked before execution."""
    has_patient_consent: bool = Field(..., description="Explicit verification of patient data sharing opt-in")
    is_clinical_automation: bool = Field(False, description="Must remain False. Guardrail against autonomous triage")

    @field_validator("is_clinical_automation")
    @classmethod
    def enforce_no_automation(cls, v: bool) -> bool:
        if v is True:
            raise ValueError("Prohibited Content Baseline: Clinical automation/triage is strictly disabled.")
        return v

class AIDraftRequest(BaseModel):
    """Validated input bound to BE-006 verified clinical fields."""
    context: AIRequestContext
    policy_gate: AIPolicyGate
    raw_symptoms: str = Field(..., min_length=10, description="Verified doctor intake notes")
    metadata: Optional[Dict[str, Any]] = Field(default_factory=dict)

class AIDraftResponse(BaseModel):
    """Deterministic, structured output schema returning safe drafts."""
    correlation_id: UUID
    drafted_summary: str = Field(..., description="The structured text draft generated by the provider")
    disclaimer: str = Field(
        default="DRAFT ONLY: Generated by Qarevo WS-AI. Must be reviewed and verified by a licensed clinician.",
        description="Mandatory compliance notice"
    )
    provider_utilized: str